### ISSUE TITLE
NPM cannot fint gatsby-plugin-cloudflare-web-analytics

### ISSUE THREAD

**Issue by ugnelis** [twentyonepenguins/gatsby-plugin-cloudflare-web-analytics#1]
Hi,

When I am trying to install this library by typing `npm install gatsby-plugin-cloudflare-web-analytics`. I get this error:

```
npm ERR! code ENOVERSIONS
npm ERR! No valid versions available for gatsby-plugin-cloudflare-web-analytics
```

I have checked https://www.npmjs.com/package/gatsby-plugin-cloudflare-web-analytics and it seems that this library doesn't exist in the NPM registry

**Comment by smncd** [comment]
Hey there! 
You're right, however as of writing the package is up and accessible on NPM again. Sorry for the inconvenience :)
